services:
  zrok-agent:
    image: docker.io/openziti/zrok2
    restart: unless-stopped
    # Esto asegura que use tus archivos de /home/jovigo/.zrok2
    user: "${UID:-1000}"
    hostname: jovigo-server-docker
    environment:
      HOME: /mnt
    entrypoint:
      - bash
      - -c
      - rm -f /mnt/.zrok2/agent.socket && exec "$@"
    command:
      - --
      - zrok2
      - agent
      - start
      - --console-address
      - 0.0.0.0
      - --console-start-port
      - "8888"
      - --console-end-port
      - "8888"
    volumes:
      - ${HOME}/.zrok2:/mnt/.zrok2

  zrok-share:
    image: docker.io/openziti/zrok2
    restart: unless-stopped
    user: "${UID:-1000}"
    depends_on:
      zrok-agent:
        condition: service_started
    environment:
      HOME: /mnt
    volumes:
      - ${HOME}/.zrok2:/mnt/.zrok2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Sintaxis correcta para la versión que usas:
    entrypoint: ["zrok2", "share", "public", "host.docker.internal:8000", "--headless"]
    # NOTA: Para usar 'ebenezer-iot', primero debemos asegurar la conexión base.
