name: Despliegue Produccion IOT

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Sincronizar codigo nuevo
        uses: actions/checkout@v4
        with:
          clean: true # Esto fuerza a Git a purgar los archivos que lanzan "unable to unlink" con permisos elevados

           # Actualizar dependencias y optimizar Laravel
           # Actualizar dependencias y optimizar Laravel
      - name: Actualizar dependencias y optimizar Laravel
        env:
          CACHE_STORE: array
          CACHE_DRIVER: array
        run: |
          cd backend
          
          # 1. Forzar la creación de los directorios vitales usando privilegios elevados
          sudo mkdir -p bootstrap/cache
          sudo mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache storage/logs
          
          # 2. Otorgar de forma forzada la propiedad al usuario del runner y permisos totales de escritura
          sudo chown -R jovi_go:www-data bootstrap/cache storage
          sudo chmod -R 775 bootstrap/cache storage
          
          # 3. Ejecutar la instalación limpia con el usuario del runner
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan optimize:clear
