name: Despliegue Produccion IOT

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1. Usar la acción oficial con limpieza forzada para solucionar los permisos denegados
      - name: Sincronizar codigo nuevo
        uses: actions/checkout@v4
        with:
          clean: true # Esto elimina de raíz cualquier archivo local conflictivo

      # 2. Actualizar dependencias y optimizar Laravel
      - name: Actualizar dependencias y optimizar Laravel
        env:
          CACHE_STORE: array
          CACHE_DRIVER: array
        run: |
          # Accedemos a la carpeta interna de tu repositorio donde se encuentra Laravel
          cd backend
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan optimize:clear
